apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-service
  labels:
    app: master-service
    component: master
spec:
  replicas: 3
  selector:
    matchLabels:
      app: master-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: master-service
        component: master
    spec:
      serviceAccountName: master-service
      containers:
      - name: master-service
        image: zetareticula/master-service:latest
        imagePullPolicy: Always
        ports:
        - name: grpc
          containerPort: 50051
        - name: metrics
          containerPort: 9090
        envFrom:
        - configMapRef:
            name: master-service-config
        - secretRef:
            name: master-service-secrets
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 1000m
            memory: 512Mi
        livenessProbe:
          exec:
            command: ["grpc_health_probe", "-addr=:50051"]
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command: ["grpc_health_probe", "-addr=:50051"]
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "master"
        effect: "NoSchedule"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - master-service
              topologyKey: "kubernetes.io/hostname"
