apiVersion: v1
kind: ServiceAccount
metadata:
  name: master-service
  labels:
    app: master-service
    component: master
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: master-service
  labels:
    app: master-service
    component: master
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: master-service
  labels:
    app: master-service
    component: master
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: master-service
subjects:
- kind: ServiceAccount
  name: master-service
  namespace: default
