apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dags-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
    storageClassName: {{ .Values.persistence.storageClass | default "standard" }}
    {{- if .Values.persistence.existingClaim }}
    existingClaim: {{ .Values.persistence.existingClaim }}
        {{- end }}
    {{- if .Values.persistence.annotations }}
    annotations:
        {{- range $key, $value := .Values.persistence.annotations }}
        {{ $key }}: "{{ $value }}"
        {{- end }}
        {{- end }}