apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-service
  labels:
    app: billing
spec:
  replicas: 2 # Initial replicas, auto-scaled by HPA
  selector:
    matchLabels:
      app: billing
  template:
    metadata:
      labels:
        app: billing
    spec:
      containers:
      - name: billing
        image: your-registry/billing-service:latest # Replace with your image
        env:
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: stripe-secrets
              key: stripe-secret-key
        - name: STRIPE_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: stripe-secrets
              key: stripe-webhook-secret
        - name: NEON_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: neon-secrets
              key: neon-connection-string
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080