[package]
name = "llm-rs"
version = "0.1.2"
edition = "2021"

[dependencies]
salience-engine = { path = "../salience-engine" }
ns-router-rs = { path = "../ns-router-rs" }
kvquant-rs = { path = "../kvquant-rs" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rayon = "1.8"
ndarray = "0.15"
log = "0.4"
dashmap = "5.5"
tokio = { version = "1.0", features = ["fs", "io-util"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1