[package]
name = "zeta-reticula"
version = "0.2.4"
edition = "2021"
description = "A k8s-native library for distributed AI inference and storage with Petri net-based agent systems"
license = "Apache-2.0"
repository = "https://github.com/zeta-reticula/zeta-reticula"

[dependencies]
# Async runtime
tokio = { version = "1", features = ["full", "rt-multi-thread"] }
async-trait = "0.1"
futures = "0.3"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
prost = "0.11"

# Concurrency
crossbeam = "0.8"
dashmap = "5.4"
parking_lot = "0.12"
rayon = { version = "1.5", features = ["crossbeam-utils"] }

# Math and ML
tch = { version = "0.9", features = ["cuda"] }
ndarray = "0.15"
rand = { version = "0.8", features = ["small_rng"] }
rand_distr = "0.4"

# Networking
tonic = { version = "0.8", features = ["tls"] }
tokio-stream = { version = "0.1", features = ["net"] }
tokio-util = { version = "0.7", features = ["codec"] }
hyper = { version = "0.14", features = ["server", "http1", "http2", "tcp"] }
http = "0.2"
http-body = "0.4"
tower = { version = "0.4", features = ["util", "timeout"] }

# Web
actix-web = "4"
actix-cors = "0.6"
jsonwebtoken = "8"

# Storage
lru = "0.7"
sqlx = { version = "0.6", features = ["runtime-tokio-native-tls", "postgres", "migrate", "chrono"] }
tokio-postgres = { version = "0.7", features = ["with-chrono-0_4"] }

# Security
rustls = "0.21"
rustls-pemfile = "1.0"

# Utilities
anyhow = "1.0"
bytes = "1.0"
chrono = { version = "0.4", features = ["serde"] }
hashbrown = "0.14"
log = "0.4"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
url = "2.2"
uuid = { version = "1.1", features = ["v4", "serde"] }

# Metrics
metrics = "0.20"
metrics-exporter-prometheus = "0.11"

# Other
clap = { version = "4", features = ["derive"] }
mlua = { version = "0.9", features = ["lua54", "vendored"] }  # Added for Lua integration

[dependencies.p2pstore]
path = "src/p2pstore"
version = "0.1.0"

[dependencies.zeta-vault-synergy]
path = "src/zeta_vault_synergy"
version = "0.2.0"

[dependencies.client]
path = "src/client"
version = "0.1.0"

[dependencies.master-service]
path = "src/master_service"
version = "0.1.0"

[dependencies.attention-store]
path = "src/attention_store"
version = "0.1.0"

[dependencies.llm-rs]
path = "src/llm_rs"
version = "0.1.0"

[dependencies.quantize]
path = "src/quantize"
version = "0.1.0"

[dependencies.agentflow]
path = "src/agentflow"
version = "0.1.0"

[[bin]]
name = "zeta-infer"
path = "src/bin/zeta-infer.rs"
[workspace]
members = [
    "api",
    "salience-engine",
    "llm-rs",
    "ns-router-rs",
    "kvquant-rs",
    "quantize-cli",
    "agentflow-rs",
    "zeta-integration"
]
resolver = "2"

