[package]
name = "zeta-reticula"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3"
serde = { version = "1.0", features = ["derive"] }
sqlx = { version = "0.7", features = ["runtime-actix-rustls", "postgres"] }
reqwest = { version = "0.11", features = ["json"] }
jsonwebtoken = "8.3"
oauth2 = { version = "4.4", features = ["reqwest"] }
prost = "0.11"
zeta = { path = "protos" }
tokio = { version = "1.32", features = ["full"] }
log = "0.4"
lru = "0.10"
once_cell = "1.18"
rlua = "0.19"  # Lua integration
pyo3 = { version = "0.19", features = ["auto-initialize"] }  # Python integration

[features]
enterprise = ["unlimited-inferences"]

[dev-dependencies]
rstest = "0.18"