[workspace]
members = [
    "shared",
    "kvquant-rs",
    "ns-router-rs",
    "llm-rs",
    "salience-engine",
    "quantize-cli",
    "api"
]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
debug = false
incremental = false
rpath = false
strip = true
panic = "abort"
overflow-checks = false

[profile.dev]
opt-level = 1
debug = true
incremental = true
overflow-checks = true
