apiVersion: apps/v1
kind: Deployment
metadata:
  name: p2pstore
  labels:
    app: p2pstore
spec:
  replicas: 3
  selector:
    matchLabels:
      app: p2pstore
  template:
    metadata:
      labels:
        app: p2pstore
    spec:
      containers:
      - name: p2pstore
        image: zetareticula/p2pstore:latest
        ports:
        - containerPort: 50051
        env:
        - name: RUST_LOG
          value: "info"
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: p2pstore-service
spec:
  selector:
    app: p2pstore
  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051
  type: ClusterIP
