apiVersion: v1
kind: LimitRange
metadata:
  name: master-service-limits
  labels:
    app: master-service
    component: master
    environment: production
spec:
  limits:
  - type: Pod
    min:
      cpu: 100m
      memory: 128Mi
    max:
      cpu: 2000m
      memory: 4Gi
  - type: Container
    default:
      cpu: 500m
      memory: 1Gi
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    max:
      cpu: 2000m
      memory: 4Gi
    min:
      cpu: 50m
      memory: 64Mi
