apiVersion: v1
kind: ResourceQuota
metadata:
  name: master-service-quota
  labels:
    app: master-service
    component: master
    environment: production
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "20"
    limits.memory: 40Gi
    pods: "50"
    services: "10"
    configmaps: "20"
    persistentvolumeclaims: "10"
    secrets: "20"
