[package]
name = "salience-engine"
version = "0.1.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
neon = "0.10"
rand = "0.8"
rand_distr = "0.4"  # For stochastic search distributions
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
itertools = "0.12"
dashmap = "5.5"  # For concurrent token processing

[profile.release]
opt-level = 3
lto = true
codegen-units = 1