{{- if .Values.configMaps }}
{{- range .Values.configMaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
  labels:
    {{- include "zeta-reticula.labels" $ | nindent 4 }}
data:
  {{- range $key, $value := .data }}
  {{ $key }}: |
    {{- $value | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- end }}
