{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "zeta-reticula.fullname" . }}
  labels:
    {{- include "zeta-reticula.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "zeta-reticula.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- range .Values.networkPolicies.ingressRules }}
    - {{ . | toYaml | nindent 6 }}
    {{- end }}
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "zeta-reticula.name" . }}
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
      ports:
        - protocol: TCP
          port: 80
  egress:
    {{- range .Values.networkPolicies.egressRules }}
    - {{ . | toYaml | nindent 6 }}
    {{- end }}
    - to:
        - namespaceSelector:
            matchLabels:
              name: kube-system
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
    - to:
        - namespaceSelector:
            matchLabels:
              name: monitoring
      ports:
        - protocol: TCP
          port: 9090
    - to: []
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 80
{{- end }}
