{{- if .Values.zetaReticula.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zeta-reticula.fullname" . }}
  labels:
    {{- include "zeta-reticula.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "zeta-reticula.selectorLabels" . | nindent 4 }}
{{- end }}