// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/sidecar.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VectorId      string                 `protobuf:"bytes,1,opt,name=vector_id,json=vectorId,proto3" json:"vector_id,omitempty"`
	LayerId       string                 `protobuf:"bytes,2,opt,name=layer_id,json=layerId,proto3" json:"layer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheRequest) Reset() {
	*x = CacheRequest{}
	mi := &file_proto_sidecar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheRequest) ProtoMessage() {}

func (x *CacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidecar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheRequest.ProtoReflect.Descriptor instead.
func (*CacheRequest) Descriptor() ([]byte, []int) {
	return file_proto_sidecar_proto_rawDescGZIP(), []int{0}
}

func (x *CacheRequest) GetVectorId() string {
	if x != nil {
		return x.VectorId
	}
	return ""
}

func (x *CacheRequest) GetLayerId() string {
	if x != nil {
		return x.LayerId
	}
	return ""
}

type CacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheResponse) Reset() {
	*x = CacheResponse{}
	mi := &file_proto_sidecar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheResponse) ProtoMessage() {}

func (x *CacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidecar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheResponse.ProtoReflect.Descriptor instead.
func (*CacheResponse) Descriptor() ([]byte, []int) {
	return file_proto_sidecar_proto_rawDescGZIP(), []int{1}
}

func (x *CacheResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CacheResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CacheUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VectorId      string                 `protobuf:"bytes,1,opt,name=vector_id,json=vectorId,proto3" json:"vector_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheUpdate) Reset() {
	*x = CacheUpdate{}
	mi := &file_proto_sidecar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheUpdate) ProtoMessage() {}

func (x *CacheUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidecar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheUpdate.ProtoReflect.Descriptor instead.
func (*CacheUpdate) Descriptor() ([]byte, []int) {
	return file_proto_sidecar_proto_rawDescGZIP(), []int{2}
}

func (x *CacheUpdate) GetVectorId() string {
	if x != nil {
		return x.VectorId
	}
	return ""
}

func (x *CacheUpdate) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_proto_sidecar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidecar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_proto_sidecar_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_sidecar_proto protoreflect.FileDescriptor

const file_proto_sidecar_proto_rawDesc = "" +
	"\n" +
	"\x13proto/sidecar.proto\x12\asidecar\"F\n" +
	"\fCacheRequest\x12\x1b\n" +
	"\tvector_id\x18\x01 \x01(\tR\bvectorId\x12\x19\n" +
	"\blayer_id\x18\x02 \x01(\tR\alayerId\";\n" +
	"\rCacheResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\">\n" +
	"\vCacheUpdate\x12\x1b\n" +
	"\tvector_id\x18\x01 \x01(\tR\bvectorId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"(\n" +
	"\x0eUpdateResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\x92\x01\n" +
	"\x0eSidecarService\x12@\n" +
	"\rGetCachedData\x12\x15.sidecar.CacheRequest\x1a\x16.sidecar.CacheResponse\"\x00\x12>\n" +
	"\vUpdateCache\x12\x14.sidecar.CacheUpdate\x1a\x17.sidecar.UpdateResponse\"\x00B,Z*github.com/zetareticula/zeta-sidecar/protob\x06proto3"

var (
	file_proto_sidecar_proto_rawDescOnce sync.Once
	file_proto_sidecar_proto_rawDescData []byte
)

func file_proto_sidecar_proto_rawDescGZIP() []byte {
	file_proto_sidecar_proto_rawDescOnce.Do(func() {
		file_proto_sidecar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sidecar_proto_rawDesc), len(file_proto_sidecar_proto_rawDesc)))
	})
	return file_proto_sidecar_proto_rawDescData
}

var file_proto_sidecar_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_sidecar_proto_goTypes = []any{
	(*CacheRequest)(nil),   // 0: sidecar.CacheRequest
	(*CacheResponse)(nil),  // 1: sidecar.CacheResponse
	(*CacheUpdate)(nil),    // 2: sidecar.CacheUpdate
	(*UpdateResponse)(nil), // 3: sidecar.UpdateResponse
}
var file_proto_sidecar_proto_depIdxs = []int32{
	0, // 0: sidecar.SidecarService.GetCachedData:input_type -> sidecar.CacheRequest
	2, // 1: sidecar.SidecarService.UpdateCache:input_type -> sidecar.CacheUpdate
	1, // 2: sidecar.SidecarService.GetCachedData:output_type -> sidecar.CacheResponse
	3, // 3: sidecar.SidecarService.UpdateCache:output_type -> sidecar.UpdateResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_sidecar_proto_init() }
func file_proto_sidecar_proto_init() {
	if File_proto_sidecar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sidecar_proto_rawDesc), len(file_proto_sidecar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sidecar_proto_goTypes,
		DependencyIndexes: file_proto_sidecar_proto_depIdxs,
		MessageInfos:      file_proto_sidecar_proto_msgTypes,
	}.Build()
	File_proto_sidecar_proto = out.File
	file_proto_sidecar_proto_goTypes = nil
	file_proto_sidecar_proto_depIdxs = nil
}
