apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
  namespace: zeta-reticula
  labels:
    app: zeta-reticula
    component: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zeta-reticula
      component: api
  template:
    metadata:
      labels:
        app: zeta-reticula
        component: api
    spec:
      containers:
      - name: api
        image: zetareticula/zeta-reticula:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: MASTER_SERVICE_URL
          value: "http://master-service.zeta-reticula.svc.cluster.local"
        - name: RUST_LOG
          value: "info"
        - name: ZETA_MODE
          value: "api"
        command: ["./target/release/zeta"]
        args: ["api", "serve", "--port", "3000", "--host", "0.0.0.0"]
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: zeta-reticula
  labels:
    app: zeta-reticula
    component: api
spec:
  ports:
  - port: 80
    targetPort: 3000
    name: http
  selector:
    app: zeta-reticula
    component: api
  type: LoadBalancer
