apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-service
  namespace: zeta-reticula
  labels:
    app: zeta-reticula
    component: master
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zeta-reticula
      component: master
  template:
    metadata:
      labels:
        app: zeta-reticula
        component: master
    spec:
      containers:
      - name: master
        image: zetareticula/zeta-reticula:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: RUST_LOG
          value: "info"
        - name: ZETA_ENV
          value: production
        - name: ZETA_MODE
          value: "master"
        command: ["./target/release/zeta"]
        args: ["master", "serve", "--port", "8080", "--host", "0.0.0.0"]
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "1"
            memory: "2Gi"
        volumeMounts:
        - name: config
          mountPath: /app/config
      volumes:
      - name: config
        configMap:
          name: zeta-config
---
apiVersion: v1
kind: Service
metadata:
  name: master-service
  namespace: zeta-reticula
  labels:
    app: zeta-reticula
    component: master
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: http
  selector:
    app: zeta-reticula
    component: master
  type: ClusterIP
