apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zeta-reticula

resources:
  - ../../base

patches:
  - path: patch-deployment.yaml

images:
  - name: zetareticula/zeta-reticula
    newTag: latest

labels:
  environment: dev
