apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-service
  namespace: zeta-reticula
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: master
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: zeta-reticula
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: worker
        resources:
          limits:
            cpu: "2"
            memory: "8Gi"
            nvidia.com/gpu: 1
          requests:
            cpu: "1"
            memory: "4Gi"
            nvidia.com/gpu: 1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zeta-config
  namespace: zeta-reticula
data:
  RUST_LOG: "debug"
  ENVIRONMENT: "development"
