[package]
name = "zeta-reticula-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3"
actix-multipart = "0.6"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["fs"] }
futures = "0.3"

[profile.release]
opt-level = 3