[package]
name = "zeta-reticula-api"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]  # Enable WASM compilation

[dependencies]
actix-web = "4.3"
actix-multipart = "0.6"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"], optional = true }  # Optional for WASM
futures = "0.3"
log = "0.4"
llm-rs = { path = "../llm-rs", features = ["wasm"] }  # Add WASM feature
salience-engine = { path = "../salience-engine", features = ["wasm"] }
tonic = "0.10"
prost = "0.12"
serde_json = "1.0"
bincode = "1.3"
thiserror = "1.0"
validator = { version = "0.16", features = ["derive"] }
wasm-bindgen = "0.2.87"  # WASM bindings
js-sys = "0.3.64"  # JavaScript interoperability
wasm-bindgen-futures = "0.4.37"  # Async support for WASM

[build-dependencies]
tonic-build = "0.10"

[features]
default = ["server"]
server = ["tokio", "actix-web", "actix-multipart"]  # Server-specific features
wasm = ["wasm-bindgen", "wasm-bindgen-futures", "llm-rs/wasm", "salience-engine/wasm"]  # WASM-specific features

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[profile.wasm-release]
inherits = "release"
opt-level = 3