name: Zeta Reticula CI/CD Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'core/**'
      - 'runtime/**'
      - 'interfaces/**'
      - 'master-service/**'
      - 'ns-router-rs/**'
      - 'salience-engine/**'
      - 'llm-rs/**'
      - 'agentflow-rs/**'
      - 'kvquant_rs/**'
      - 'shared/**'
      - 'attention-store/**'
      - 'scheduler/**'
      - 'k8s/**'
      - '.github/workflows/ci-cd.yaml'
      - 'Dockerfile*'
      - 'Cargo.toml'
      - 'Cargo.lock'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'core/**'
      - 'runtime/**'
      - 'interfaces/**'
      - 'master-service/**'
      - 'ns-router-rs/**'
      - 'salience-engine/**'
      - 'llm-rs/**'
      - 'agentflow-rs/**'
      - 'kvquant_rs/**'
      - 'shared/**'
      - 'attention-store/**'
      - 'scheduler/**'
      - 'k8s/**'
      - '.github/workflows/ci-cd.yaml'
      - 'Dockerfile*'
      - 'Cargo.toml'
      - 'Cargo.lock'

env:
  AWS_REGION: us-west-2
  ECR_REPOSITORY: zeta-reticula
  EKS_CLUSTER: zeta-reticula-production
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Set up Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt, clippy
          target: x86_64-unknown-linux-gnu

      - name: Cache Cargo registry and target
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build and test workspace
        run: |
          # Build the unified CLI first
          cargo build --bin zeta
          
          # Test the entire workspace
          cargo test --workspace --all-features
          
          # Test CLI functionality
          ./target/debug/zeta system status
          ./target/debug/zeta --help

  publish-crates:
    name: Verify Published Crates
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt, clippy
          target: x86_64-unknown-linux-gnu

      - name: Cache Cargo registry and target
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Verify published crates
        run: |
          # Check that all crates are published and accessible
          cargo search zeta-kv-cache --limit 1
          cargo search zeta-quantization --limit 1
          cargo search zeta-salience --limit 1
          cargo search zeta-shared --limit 1
          cargo search zeta-inference --limit 1
          cargo search zeta-reticula --limit 1

          # Test that CLI builds with published dependencies
          cargo build --bin zeta
          ./target/debug/zeta system status

  security-scan:
    name: Security Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Run cargo audit
        run: cargo audit

      - name: Run cargo clippy
        run: cargo clippy --all-features -- -D warnings

      - name: Check for security advisories
        run: cargo audit --ignore-yanked

  performance-benchmark:
    name: Performance Benchmarking
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt, clippy

      - name: Cache Cargo registry and target
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Run performance benchmarks
        run: |
          # Build release binary
          cargo build --release --bin zeta

          # Run basic performance test
          ./target/release/zeta infer benchmark \
            --iterations 100 \
            --output benchmark-results.json

      - name: Upload benchmark results
        uses: actions/upload-artifact@v3
        with:
          name: benchmark-results
          path: benchmark-results.json

  validate-k8s:
    name: Validate Kubernetes Manifests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin/

      - name: Install kubeconform
        run: |
          set -euxo pipefail
          KUBECONFORM_VER=v0.6.7
          curl -L "https://github.com/yannh/kubeconform/releases/download/${KUBECONFORM_VER}/kubeconform-linux-amd64.tar.gz" \
            | tar -xz
          sudo mv kubeconform /usr/local/bin/

      - name: Validate Kubernetes manifests (schema + structure)
        run: |
          set -euxo pipefail
          # Validate base
          kustomize build k8s/base/ | kubeconform -strict -summary -ignore-missing-schemas
          # Validate dev
          kustomize build k8s/overlays/dev/ | kubeconform -strict -summary -ignore-missing-schemas
          # Validate prod
          kustomize build k8s/overlays/prod/ | kubeconform -strict -summary -ignore-missing-schemas
          # Validate master-service k8s if exists
          if [ -d "master-service/k8s/base" ]; then
            kustomize build master-service/k8s/base/ | kubeconform -strict -summary -ignore-missing-schemas
          fi

  build:
    name: Build and Push Docker Images
    needs: [test, validate-k8s, security-scan, performance-benchmark, publish-crates]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.ECR_REPOSITORY }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha,format=long

      - name: Build and push workspace
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.optimized
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Deploy to EKS
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Update kubeconfig
        run: |
          aws eks --region ${{ env.AWS_REGION }} update-kubeconfig \
            --name ${{ env.EKS_CLUSTER }} \
            --kubeconfig kubeconfig

      - name: Deploy to Kubernetes
        run: |
          export KUBECONFIG=./kubeconfig

          # Install kustomize
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin/

          # Deploy with improved rollout strategy
          kubectl apply -k k8s/overlays/prod

          # Wait for deployments with better error handling
          kubectl rollout status deployment/api-service -n zeta-reticula --timeout=600s
          kubectl rollout status deployment/master-service -n zeta-reticula --timeout=600s
          kubectl rollout status deployment/worker -n zeta-reticula --timeout=600s
          kubectl rollout status statefulset/p2pstore -n zeta-reticula --timeout=600s

          # Verify deployment health
          kubectl get pods -n zeta-reticula
          kubectl get services -n zeta-reticula

  notify:
    name: Notify Status
    needs: [test, validate-k8s, security-scan, performance-benchmark, publish-crates, build, deploy]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_TITLE: "Deployment ${{ job.status }} for ${{ github.repository }}"
          SLACK_MESSAGE: "${{ github.workflow }} run ${{ github.run_id }} completed with ${{ job.status }}"
          SLACK_COLOR: ${{ job.status == 'success' && 'good' || 'danger' }}
          MSG_MINIMAL: "${{ job.status }}: ${{ github.workflow }} #${{ github.run_id }} (${{ github.sha }})"
          SLACK_USERNAME: GitHub Actions
          SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
